name: Publish

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - "domains/**"
            - ".github/workflows/deploy.yml"
            - "scripts/dnsconfig.js"

concurrency:
    group: ${{ github.ref }}-publish
    cancel-in-progress: false

jobs:
    dns:
        name: DNS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - run: echo '{"cloudflare":{"TYPE":"CLOUDFLAREAPI","apitoken":"$CLOUDFLARE_API_TOKEN"}}' > ./creds.json
            - uses: gacts/install-dnscontrol@v1
              with:
                  version: 4.44.1
            - name: Push DNS Records
              run: dnscontrol push --config ./scripts/dnsconfig.js --creds ./creds.json