name: Validation

on:
    workflow_dispatch:
      inputs:
        pr_number:
          description: 'PR number to check (optional)'
          type: string
          required: false
    pull_request:
      types: [opened, synchronize, reopened, labeled, unlabeled]
    push:
        paths:
            - "domains/**"
            - ".github/workflows/validation.yml"
            - "scripts/**"

concurrency:
    group: ${{ github.ref }}-validation
    cancel-in-progress: true
    
permissions:
  contents: read
  pull-requests: read
  
jobs:
    dns:
        name: DNS
        runs-on: ubuntu-latest
        env:
            CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        steps:
            - uses: actions/checkout@v7
            - name: Write DNSControl creds
              run: |
                cat > ./creds.json <<EOF
                {"cloudflare":{"TYPE":"CLOUDFLAREAPI","apitoken":"${CLOUDFLARE_API_TOKEN}"}}
                EOF
            - uses: gacts/install-dnscontrol@v1
              with:
                  version: 4.44.1
            - name: Push DNS Records
              run: dnscontrol check --config ./scripts/dnsconfig.js

    json:
        name: JSON
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: oven-sh/setup-bun@v2
              with:
                bun-version: v1.3.13
            - run: bun test
              env:
                PR_NUMBER: ${{ github.event.pull_request.number }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
