name: Validation

on:
    workflow_dispatch:
    pull_request:
    push:
        paths:
            - "domains/**"
            - ".github/workflows/validation.yml"
            - "scripts/*"

concurrency:
    group: ${{ github.ref }}-validation
    cancel-in-progress: true

jobs:
    dns:
        name: DNS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - run: echo '{"cloudflare":{"TYPE":"CLOUDFLAREAPI","apitoken":"$CLOUDFLARE_API_TOKEN"}}' > ./creds.json
            - uses: gacts/install-dnscontrol@v1
              with:
                  version: 4.44.1
            - name: Push DNS Records
              run: dnscontrol check --config ./scripts/dnsconfig.js --creds ./creds.json

    json:
        name: JSON
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: JSON Syntax Check
              uses: limitusus/json-syntax-check@v2
              with:
                  pattern: "\\.json$"
              env:
                  BASE: "domains/"
            - name: Validate JSON Schema
              uses: cardinalby/schema-validator-action@v3
              with:
                file: 'domains/**/*.json'
                schema: 'scripts/schema.json'
